### ISSUE TITLE
WebDAVで書き込みができません

### ISSUE THREAD

**Issue by tiramik** [matsumoto-r/mod_process_security#14]
はじめまして。
mod_process_securityにてCGIやPHPなどの動的コンテンツおよびhtmlなどの静的コンテンツのvHostのDocumentRootオーナーによる動作を確認できました。現在は動作検証中の段階です。

環境はApache2.4.6 (CentOS7.1)で、各VirtualHostディレクティブの真下に下記のように記述しております。
```
     <IfModule mod_process_security.c>  
     PSExAll On  
    </IfModule>  
```
また、グローバル設定である、/etc/httpd/conf.d/mod_process_security.conf
では下記のようにLoadModuleのみ有効にした状態です。
```
LoadModule process_security_module /usr/lib64/httpd/modules/mod_process_security.so
#<IfModule mod_process_security.c>  
#  PSExAll On  
#</IfModule>  
```
しかし、本moduleを有効にするとvHost内で定義しているvHostオーナーのWebDAVフォルダ（permission:771)に書き込みできず、下記のようなエラーが記録されます。
* A lock database was not specified with the DAVLockDB directive. One must be specified to use the locking functionality.  [500, #401]
* The lock database could not be opened, preventing access to the various lock properties for the PROPFIND.  [500, #0]

もちろんDAVLockDB のオーナーやパーミッションに問題はなく、mod_ruid2を使った場合は問題なくWebDAVクライアントで書き込めますし、その時の新規作成ファイルは正常にvHostのオーナーとなります。
また、このフォルダやロックディレクトリ/ロックファイルを777にしてもmod_process_securityだと上記エラーで書き込めません。

ちなみに、ちょっと話が逸れますが、このオーナーのWebDAVフォルダをpermission:770にするとフォルダの読み取りすらできなくなります。
また通常のWebサイト部分もディレクトリのパーミッションが700や770だと配下のファイルにブラウザがアクセスできず、701や771にする必要があるようです。
これはこれで正しい気はするのですが、mod_ruid2であれば700でも配下のファイルは参照可能である事を確認しました。
（mod_process_securityでも、フォルダではなくファイルであれば600でも参照可能でした。）

以上のような報告ですが、何か対処法はあるでしょうか？
本moduleのディレクティブは[PSExAll On]くらいしか使ってませんが、他に使用すべきものが分かりませんでした。

mod_ruid2ではやはりセキュリティに不安が残るということと、mod_fcgid+suEXEC構成だと静的コンテンツやWebDAVでのファイルオーナーの不都合が出ます。
甘いのかもしれませんが、是非mod_process_securityで全てを叶えたいと思っていますので、アドバイスをいただければと思います。

**Comment by matsumoto-r** [comment]
詳細な情報ありがとうございます。

少し考えたのですが、webdavを対応させようとするとファイルの新規作成への対応などが必要となり、mod_process_securityの基本的なアーキテクチャ（リクエストファイルのownerを取得する所など）とはズレてくるので、webdav対応は別のモジュールに任せた方が良いように思いました。

mod_ruid2で使えるのであれば、mod_ruid2で処理していただくのがよさそうです。その際のセキュリティ周りについては別途きちんと議論すべきだと思いますが、それはmod_ruid2の話になると思いますので、ここでのissueでは省略します。

**Comment by tiramik** [comment]
バタバタしていてご連絡が遅くなりました。申し訳ありません。

方針について承知しました。
davについては一部の用途では、スマホアプリでの連携などまだまだ有用だと考えているので、mod_ruid2で検討する事にします。
PSモジュールで可能なのであれば一番良かったのですが仕方ないですね。
dav対応のモジュールも期待しています(笑)。

ありがとうございました。

**Comment by k0u5uk3** [comment]
@tiramik さん　以下のPRにてmod-process-securityのwebdav対応を行いましたので、よかったらご確認ください。

https://github.com/matsumoto-r/mod_process_security/pull/18
